/**
 * Sound effects, synthesised in the browser.
 *
 * Every tone is generated by an oscillator — there is no audio file to load,
 * so the game stays a zero-request page. The context is created lazily on the
 * first flip, which is a user gesture, so autoplay policy is satisfied without
 * a "click to enable sound" prompt.
 */

export type Cue = "flip" | "match" | "miss" | "win";

interface Note {
  frequency: number;
  /** Seconds from the start of the cue. */
  at: number;
  duration: number;
  type: OscillatorType;
  gain: number;
}

const CUES: Record<Cue, Note[]> = {
  flip: [{ frequency: 520, at: 0, duration: 0.07, type: "triangle", gain: 0.05 }],
  match: [
    { frequency: 659.25, at: 0, duration: 0.1, type: "sine", gain: 0.07 },
    { frequency: 987.77, at: 0.09, duration: 0.16, type: "sine", gain: 0.06 },
  ],
  miss: [{ frequency: 155, at: 0, duration: 0.13, type: "sawtooth", gain: 0.035 }],
  win: [
    { frequency: 523.25, at: 0, duration: 0.16, type: "sine", gain: 0.07 },
    { frequency: 659.25, at: 0.12, duration: 0.16, type: "sine", gain: 0.07 },
    { frequency: 783.99, at: 0.24, duration: 0.18, type: "sine", gain: 0.07 },
    { frequency: 1046.5, at: 0.36, duration: 0.42, type: "sine", gain: 0.08 },
  ],
};

type AudioContextConstructor = new () => AudioContext;

let context: AudioContext | null = null;

function audio(): AudioContext | null {
  if (typeof window === "undefined") return null;

  const Ctor: AudioContextConstructor | undefined =
    window.AudioContext ??
    (window as unknown as { webkitAudioContext?: AudioContextConstructor })
      .webkitAudioContext;
  if (!Ctor) return null;

  try {
    if (!context) context = new Ctor();
    if (context.state === "suspended") void context.resume();
    return context;
  } catch {
    // Audio is a garnish. If the browser refuses, the game is unaffected.
    return null;
  }
}

export function play(cue: Cue): void {
  const ctx = audio();
  if (!ctx) return;

  for (const note of CUES[cue]) {
    try {
      const oscillator = ctx.createOscillator();
      const envelope = ctx.createGain();
      const start = ctx.currentTime + note.at;
      const end = start + note.duration;

      oscillator.type = note.type;
      oscillator.frequency.setValueAtTime(note.frequency, start);

      // A hard start or stop on a gain node clicks; ramp both ends.
      envelope.gain.setValueAtTime(0.0001, start);
      envelope.gain.exponentialRampToValueAtTime(note.gain, start + 0.012);
      envelope.gain.exponentialRampToValueAtTime(0.0001, end);

      oscillator.connect(envelope).connect(ctx.destination);
      oscillator.start(start);
      oscillator.stop(end + 0.02);
    } catch {
      return;
    }
  }
}
